from enum import StrEnum


class UserRole(StrEnum):
    CITIZEN = "citizen"
    AGENCY_STAFF = "agency_staff"
    ADMIN = "admin"


class TicketCategory(StrEnum):
    POTHOLE = "POTHOLE"
    ROAD_DAMAGE = "ROAD_DAMAGE"
    STREETLIGHT_OUTAGE = "STREETLIGHT_OUTAGE"
    TRAFFIC_SIGNAL = "TRAFFIC_SIGNAL"
    SIDEWALK_OBSTRUCTION = "SIDEWALK_OBSTRUCTION"
    ACCESSIBILITY_BARRIER = "ACCESSIBILITY_BARRIER"
    ILLEGAL_DUMPING = "ILLEGAL_DUMPING"
    TRASH_OVERFLOW = "TRASH_OVERFLOW"
    PARK_DAMAGE = "PARK_DAMAGE"
    FLOODING = "FLOODING"
    GRAFFITI = "GRAFFITI"
    ABANDONED_VEHICLE = "ABANDONED_VEHICLE"
    NOISE_COMPLAINT = "NOISE_COMPLAINT"
    WATER_LEAK = "WATER_LEAK"
    OTHER = "OTHER"


class AgencyType(StrEnum):
    PUBLIC_WORKS = "PUBLIC_WORKS"
    ELECTRIC_UTILITY = "ELECTRIC_UTILITY"
    TRANSPORTATION = "TRANSPORTATION"
    SANITATION = "SANITATION"
    PARKS = "PARKS"
    WATER_SERVICES = "WATER_SERVICES"
    CODE_ENFORCEMENT = "CODE_ENFORCEMENT"
    PARKING_ENFORCEMENT = "PARKING_ENFORCEMENT"
    UNASSIGNED = "UNASSIGNED"


class Severity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class TicketStatus(StrEnum):
    ROUTED = "ROUTED"
    IN_PROGRESS = "IN_PROGRESS"
    NEEDS_MORE_INFO = "NEEDS_MORE_INFO"
    RESOLVED = "RESOLVED"
